### ISSUE TITLE
Support dataset.filter sample filtering

### ISSUE THREAD

**Issue by mpetri** [mosaicml/streaming#247]
## 🚀 Feature Request

One of the nice things about the streaming dataset from huggingface is that you can filter samples: 

https://huggingface.co/docs/datasets/stream#filter

Is this possible with this streamdataset implementation?

**Comment by karan6181** [comment]
Hi @mpetri , thanks for filing an issue. 

The dataset filtration on the fly is in our roadmap and we will look into it on how we can prioritize this feature. As of today, there is no single API to filter the dataset. However, one of the way I think of right now is that you can always create a custom dataset class by inheriting `StreamingDataset` and then override `__getitem__()` method where you can add any filter logic you want. One catch with this approach is that the iterator still runs for the total sample times rather than the total filtered sample times.

**Comment by mpetri** [comment]
Thanks. Looking forward to the feature.  Should I close this issue?

**Comment by karan6181** [comment]
@mpetri Yes please, feel free to close the issue. We will let you know once this feature is shipped. Thank you for your interest in streaming.
