### ISSUE TITLE
Reading all formats (parquet, csv, tsv, json) etc natively without conversion steps 

### ISSUE THREAD

**Issue by abhijithneilabraham** [mosaicml/streaming#678]
Is it possible to simply upload a file or folder of parquet, csv, tsv, json etc and stream it, without the requirement of an index.json? It's basically an additional conversion step to have it converted, why not remove this step entirely?

**Comment by snarayan21** [comment]
Hey @abhijithneilabraham, we require the `index.json` file to store metadata about the dataset so that it can be constructed in a way that gives us deterministic training and fast resumption. When a StreamingDataset is instantiated, it downloads the index.json files from every stream, and uses this metadata to construct the dataset deterministically once `__iter__` is called.

I'm going to close out this issue if that makes sense to you!

**Comment by abhijithneilabraham** [comment]
Thank You for the clarification.
