### ISSUE TITLE
Different batch_size for different streams

### ISSUE THREAD

**Issue by huxuan** [mosaicml/streaming#698]
## 🚀 Feature Request

Currently, the batch size for different streams are the same, it would be better to be able to configure them especially for cases with `per_stream` batching method. 

## Motivation

Considering the cases we have different types of data and we want to adjust the batch_size so as to maximize the GPU usage.

## Additional context

If might be possible to mix two different dataloaders, but I wonder whether there is a recommended approach or even official support for that.

**Comment by snarayan21** [comment]
Hey @huxuan, currently `per_stream` batching doesn't support different batch sizes for different streams, and we don't plan to in the future because this would require heavy modification of the current partitioning logic, and can be supported through other means. For example, one thing you could do, as you mention, is use two dataloaders, get the iterators for them, and call `next` in a round-robin or random fashion. Another thing you could try is wrapping multiple streaming datasets in another IterableDataset, which could be something like this:

```
class MyDataset(IterableDataset):
    def __init__(self, local1, remote1, local2, remote2):
        self.dataset_1 = StreamingDataset(local1, remote1, ...)
        self.dataset_2 = StreamingDataset(local2, remote2, ...)
        self.step_index = 0
        
    def __getitem__(self, index):
        iter_dataset_1 = iter(self.dataset_1)
        iter_dataset_2 = iter(self.dataset_2)
        if self.step_index % 0:
            yield next(iter_dataset_1)
        else:
            yield next(iter_dataset_2)
```

Hope this helps!

**Comment by huxuan** [comment]
Thanks for the response. The key problem is to maintain some features like fast resume, so it would be great to have some kind of official supported solutions. Maybe in the form of tests or documentation? Anyway, I will try the mentioned approaches and may come back with a more complete solution. Just close the issue now.
