### ISSUE TITLE
[Question] StreamingOutsideDTWebVid cache_limit for video

### ISSUE THREAD

**Issue by nagadit** [mosaicml/streaming#732]
Do I understand correctly that the cache_limit parameter only works for MDS shards and does not index [extra_local](https://github.com/mosaicml/streaming/blob/5f939c9057b041f10342dfc5744d2d3880e3f14b/streaming/multimodal/webvid.py#L207) for downloading videos?

https://github.com/mosaicml/streaming/blob/5f939c9057b041f10342dfc5744d2d3880e3f14b/streaming/multimodal/webvid.py#L210

If so, is it possible to clear the folder from old videos using an additional cache_limit ?

Best Regard, Alex.

**Comment by nagadit** [comment]
Thanks for the answer!
I have another question, is it possible to work with ZIP or TAR archives as it is implemented in the webdataset library?

https://github.com/webdataset/webdataset

**Comment by snarayan21** [comment]
Hey, we don't offer direct support for zip or tar since Streaming requires the data to be in a predictable format (as written by our Writer classes, such as MDSWriter, JSONWriter, CSVWriter, etc) so that the dataset knows how to access particular samples with very low latency.

However, the Writer classes do offer compression of shards if you want to save space. See [this section](https://docs.mosaicml.com/projects/streaming/en/stable/preparing_datasets/basic_dataset_conversion.html) in the docs for more info on writing datasets & compression.
